apiVersion: apps/v1
kind: Deployment
metadata:
    name: shop-app
spec:
    selector:
      matchLabels:
        app: shop-app
    template:
      metadata:
        labels:
            app: shop-app
      spec:
        containers:
        - name: shop-app
          image: {{ .Values.image }}
